/*
    West Java Cops and Robbers Modules
 */

// config
#include "modules\server\server_logs.pwn"
#include "modules\server\config\database.pwn"
#include "modules\server\config\server_config.pwn"
#include "modules\server\config\colors.pwn"

// anticheat
#include "modules\server\anticheat\mainanticheat.pwn"

//server stuff
#include "modules\server\server_functions.pwn"
#include "modules\server\security.pwn"
#include "modules\server\floodcontrols.pwn"
#include "modules\server\server_vars.pwn"

#include "modules\server\game_time.pwn"
